# Set up directory for zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet.
if [ ! -d "$ZINIT_HOME" ]; then 
    mkdir -p "$(dirname $ZINIT_HOME)"
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source zinit.
source "${ZINIT_HOME}/zinit.zsh"

# Add git plugin.
# zi snippet OMZL::git.zsh
# zi snippet OMZP::git
# zi cdclear -q

# Set theme.
zinit snippet https://github.com/mrdebator/an.sh/blob/main/themes/mrdebator.zsh-theme
# zi snippet OMZT::agnoster

# Add zsh plugins.
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions

# Load completions.
autoload -Uz compinit && compinit
zinit cdreplay -q

# History Optimizations
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Allow case-insensitive autocompletions
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# Add color to autocompletions
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Aliases
