# =======================================================================
# FONT CONFIGURATION
# =======================================================================

[font]
# Font size (can be an integer or float)
size = 18.0

# The normal (default) font face configuration.
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# The bold font face configuration.
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# The italic font face configuration.
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
